const hotCoffeeData = {
    'BlackCoffee': {
                    'Types': {
                              'LatteCoffee': {
                                              'image': '',
                                              'description': '',
                                              'ingredients': '',},
                          'CappuccinoCoffee': {
                                               'image': '',
                                               'description': '',
                                               'ingredients': '',},
                           'AmericanoCoffee': {
                                               'image': '',
                                               'description': '',
                                               'ingredients': '',},
                              'DoppioCoffee': {
                                               'image': '',
                                               'description': '',
                                               'ingredients': '',},
                             'CortadoCoffee': {
                                               'image': '',
                                               'description': '',
                                               'ingredients': '',},
                              'RedEyeCoffee': {
                                               'image': '',
                                               'description': '',
                                               'ingredients': '',},
                               'GalaoCoffee': {
                                               'image': '',
                                               'description': '',
                                               'ingredients': '',}
                            }},
    'LatteCoffee': {
                    'Types': {
                                'LatteCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CappuccinoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'AmericanoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'DoppioCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CortadoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'RedEyeCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'GalaoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',}
                            }},
    'CappuccinoCoffee': { 
                         'Types': {
                                    'LatteCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                'CappuccinoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                'AmericanoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                    'DoppioCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                'CortadoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                    'RedEyeCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                    'GalaoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',}
                                }},
    'AmericanoCoffee': { 
                        'Types': {
                                    'LatteCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                'CappuccinoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                'AmericanoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                    'DoppioCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                'CortadoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                    'RedEyeCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',},
                                    'GalaoCoffee': {
                                                    'image': '',
                                                    'description': '',
                                                    'ingredients': '',}
                                }},
    'DoppioCoffee': { 
                    'Types': {
                                'LatteCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CappuccinoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'AmericanoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'DoppioCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CortadoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'RedEyeCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'GalaoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',}
                            }},
    'CortadoCoffee': { 
                    'Types': {
                                'LatteCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CappuccinoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'AmericanoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'DoppioCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CortadoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'RedEyeCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'GalaoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',}
                            }},
    'RedEyeCoffee': { 
                    'Types': {
                                'LatteCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CappuccinoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'AmericanoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'DoppioCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CortadoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'RedEyeCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'GalaoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',}
                            }},
    'GalaoCoffee': { 
                    'Types': {
                                'LatteCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CappuccinoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'AmericanoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'DoppioCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                            'CortadoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'RedEyeCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',},
                                'GalaoCoffee': {
                                                'image': '',
                                                'description': '',
                                                'ingredients': '',}
                            }}
}
 const coldCoffeeData = {}
// const hotTeasData = {}
// const coldTeasdata = {}

export {hotCoffeeData, coldCoffeeData }
// 'Black Coffee','https://images.unsplash.com/photo-1521302080334-4bebac2763a6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YmxhY2slMjBjb2ZmZWV8ZW58MHx8MHx8&w=1000&q=80'], 
//                         ['Latte Coffee', 'https://thumbs.dreamstime.com/b/black-coffee-cup-art-latte-froth-tulip-shaped-isolated-white-background-clipping-path-225258642.jpg'],
//                         ['Cappuccino Coffee', 'https://www.shutterstock.com/image-photo/cup-art-latte-on-cappuccino-260nw-1323112487.jpg'],
//                         ['Americano Coffee', 'https://www.shutterstock.com/image-photo/coffee-drink-after-roasting-beans-260nw-1948127311.jpg'],
//                         ['Espresso Coffee', 'https://media.istockphoto.com/id/1148733827/photo/mug-with-espresso-coffee-isolated.jpg?s=612x612&w=0&k=20&c=ZMUn9VOR5UShUu8qhTIH2nvuPymbesiueNLmxs-n2n8=' ],
//                         ['Doppio Coffee', 'https://www.shutterstock.com/image-photo/espresso-doppio-cup-black-strong-260nw-1472724122.jpg' ],
//                         ['Cortado Coffee', 'https://www.acouplecooks.com/wp-content/uploads/2021/08/Cortado-004.jpg'],
//                         ['Red Eye Coffee',  'https://coffeeaffection.com/wp-content/uploads/2020/12/Black-Coffee.jpg' ],
//                         ['Galao Coffee',  'https://www.nestleprofessional.in/sites/default/files/2021-08/Galao.jpg']